language: php

services:
    - mysql

php:
    - 5.6
    - 7
    - hhvm

before_script:
    - composer self-update
    - composer install
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
    - app/console c:c -e test
    - app/console propel:database:create -e test

script:
    - phpunit --coverage-clover build/logs/clover.xml -c app

after_script:
    - travis_retry php coveralls.phar -v
