language: php

php:
    - 5.6
    - 7
    - hhvm

before_script:
    - composer self-update
    - composer install
    - composer require satooshi/php-coveralls
    - app/console c:c -e test

script:
    - phpunit -c app 

after_script:
    - travis_retry php vendor/bin/coveralls -v
